[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Hashem Hashem <hashemmm96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
structopt = "0.3.3"
